[package]
org = "wso2"
name = "inventory_management"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.obj.lineitems"
version = "0.1.0"
repository = "local"